targets = [
  { type = "constructor" , value = "Test" },
  { type = "constructor" , value = "Instrumented" },
  { type = "constraints", value = ["Eq", "Read _"] },
  { type = "constraints" , value = ["MonadTracer", "MonadUnliftIO"] }
]

exclusions = [
  { type = "constructor", value = "IO" }
]
